#! /bin/bash
clear
IMDB_HOME=/home/tore/Fotoarkiv
if [[ $1 ]]; then
  IMDB_HOME=$1
fi
echo IMDB_HOME = $IMDB_HOME
echo -n "##### Starting the Node server "`date`
# Note that Node may be installed as either 'node' or 'nodejs' :)
nodejs server.js $IMDB_HOME # Passed as/to an environment variable (see server.js)
