#! /bin/bash
clear
prodcat="../public/"

#savecat="../public/imdb/"
# Save the image database
#mkdir /tmp/savecat/ 2>/dev/null
#cp -v ${savecat}* /tmp/savecat/

# Build production catalog
ember b -prod --output-path=$prodcat

# Restore the image database
#mkdir $savecat
#cp -v /tmp/savecat/* $savecat
#sudo chmod -R 777 $savecat

# Insert a message line in index.html
echo "Inserting build timestamp ..."
mestxt='BUILD '`date +%y%m%d-%H%M`
echo $mestxt
cat ${prodcat}index.html | sed "s&\ *<body>\$&<body><div id=\"timeStamp\">$mestxt</div>&" > /tmp/index.html
cp -v /tmp/index.html ${prodcat}index.html
echo "Done."
